"""immutable_schema_snapshot

Revision ID: 20260905_0002
Revises: 20260905_0001
Create Date: 2026-09-05 12:08:54.471946
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

revision: str = '20260905_0002'
down_revision: Union[str, None] = '20260905_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_policies',
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('action')
    )
    op.create_table('commands',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('executor', sa.String(length=20), nullable=False),
    sa.Column('target_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False),
    sa.Column('initiator', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('lease_token_hash', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_action'), 'commands', ['action'], unique=False)
    op.create_index(op.f('ix_commands_created_at'), 'commands', ['created_at'], unique=False)
    op.create_index(op.f('ix_commands_executor'), 'commands', ['executor'], unique=False)
    op.create_index(op.f('ix_commands_idempotency_key'), 'commands', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_commands_initiator'), 'commands', ['initiator'], unique=False)
    op.create_index(op.f('ix_commands_source'), 'commands', ['source'], unique=False)
    op.create_index(op.f('ix_commands_status'), 'commands', ['status'], unique=False)
    op.create_index(op.f('ix_commands_task_id'), 'commands', ['task_id'], unique=False)
    op.create_table('desktop_launch_log',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('completion_hash', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('client', sa.String(length=32), nullable=False),
    sa.Column('initiator', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('completion_hash')
    )
    op.create_index(op.f('ix_desktop_launch_log_created_at'), 'desktop_launch_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_desktop_launch_log_expires_at'), 'desktop_launch_log', ['expires_at'], unique=False)
    op.create_index(op.f('ix_desktop_launch_log_host'), 'desktop_launch_log', ['host'], unique=False)
    op.create_index(op.f('ix_desktop_launch_log_initiator'), 'desktop_launch_log', ['initiator'], unique=False)
    op.create_index(op.f('ix_desktop_launch_log_status'), 'desktop_launch_log', ['status'], unique=False)
    op.create_index(op.f('ix_desktop_launch_log_task_id'), 'desktop_launch_log', ['task_id'], unique=False)
    op.create_index(op.f('ix_desktop_launch_log_token_hash'), 'desktop_launch_log', ['token_hash'], unique=True)
    op.create_table('job_log',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('command_type', sa.String(length=50), nullable=False),
    sa.Column('target_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mode', sa.String(length=20), server_default='auto', nullable=False),
    sa.Column('initiator', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_log_command_type'), 'job_log', ['command_type'], unique=False)
    op.create_index(op.f('ix_job_log_created_at'), 'job_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_log_idempotency_key'), 'job_log', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_job_log_initiator'), 'job_log', ['initiator'], unique=False)
    op.create_index(op.f('ix_job_log_source'), 'job_log', ['source'], unique=False)
    op.create_index(op.f('ix_job_log_status'), 'job_log', ['status'], unique=False)
    op.create_index(op.f('ix_job_log_task_id'), 'job_log', ['task_id'], unique=False)
    op.create_table('rule_audit_log',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('diff_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_audit_log_changed_by'), 'rule_audit_log', ['changed_by'], unique=False)
    op.create_index(op.f('ix_rule_audit_log_created_at'), 'rule_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_rule_audit_log_entity_id'), 'rule_audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_rule_audit_log_entity_type'), 'rule_audit_log', ['entity_type'], unique=False)
    op.create_table('security_audit_log',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_log_created_at'), 'security_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_audit_log_event_type'), 'security_audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_log_outcome'), 'security_audit_log', ['outcome'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_table('task_knowledge_base',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('problem', sa.String(), nullable=False),
    sa.Column('solution', sa.String(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('classification_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('quality_score', sa.Float(), server_default='1.0', nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_knowledge_base_quality_score'), 'task_knowledge_base', ['quality_score'], unique=False)
    op.create_index(op.f('ix_task_knowledge_base_task_id'), 'task_knowledge_base', ['task_id'], unique=False)
    op.execute(
        "CREATE INDEX idx_task_kb_hnsw ON task_knowledge_base "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )
    op.create_table('triage_audit_log',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('generated_comment', sa.Text(), nullable=True),
    sa.Column('final_comment', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('diff_ratio', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('operator_id', sa.String(length=100), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_audit_log_created_at'), 'triage_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_triage_audit_log_operator_id'), 'triage_audit_log', ['operator_id'], unique=False)
    op.create_index(op.f('ix_triage_audit_log_task_id'), 'triage_audit_log', ['task_id'], unique=False)
    op.create_table('triage_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('conditions_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('target_template_key', sa.String(length=64), nullable=False),
    sa.Column('actions_override_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_rules_priority'), 'triage_rules', ['priority'], unique=False)
    op.create_table('triage_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), server_default='in_work', nullable=False),
    sa.Column('status_id', sa.Integer(), server_default='27', nullable=False),
    sa.Column('status_name', sa.String(length=100), server_default='В работе', nullable=False),
    sa.Column('expenses', sa.Integer(), server_default='10', nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_templates_key'), 'triage_templates', ['key'], unique=True)
    op.create_table('users',
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_login', sa.String(), nullable=False),
    sa.Column('is_password_b64', sa.String(), nullable=False),
    sa.Column('is_user_id', sa.Integer(), nullable=True),
    sa.Column('last_task_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_comment_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_check_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tg_user_id')
    )
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=False)
    op.create_table('command_approvals',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('command_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_approvals_command_id'), 'command_approvals', ['command_id'], unique=False)
    op.create_index(op.f('ix_command_approvals_operator'), 'command_approvals', ['operator'], unique=False)
    op.create_table('command_attempts',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('command_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id', 'attempt_no', name='uq_command_attempt_no')
    )
    op.create_index(op.f('ix_command_attempts_command_id'), 'command_attempts', ['command_id'], unique=False)
    op.create_table('command_events',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('command_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id', 'sequence', name='uq_command_event_sequence')
    )
    op.create_index(op.f('ix_command_events_command_id'), 'command_events', ['command_id'], unique=False)
    op.create_index(op.f('ix_command_events_created_at'), 'command_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_command_events_event_type'), 'command_events', ['event_type'], unique=False)
    op.create_table('command_inbox',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('command_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('consumer', sa.String(length=100), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('outbox_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer', 'message_id', name='uq_command_inbox_message')
    )
    op.create_index(op.f('ix_command_inbox_command_id'), 'command_inbox', ['command_id'], unique=False)
    op.create_index(op.f('ix_command_inbox_outbox_id'), 'command_inbox', ['outbox_id'], unique=False)
    op.create_index(op.f('ix_command_inbox_received_at'), 'command_inbox', ['received_at'], unique=False)
    op.create_table('command_outbox',
    sa.Column('id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('command_id', sa.Uuid().with_variant(sa.UUID(), 'postgresql'), nullable=False),
    sa.Column('stream', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_outbox_available_at'), 'command_outbox', ['available_at'], unique=False)
    op.create_index(op.f('ix_command_outbox_command_id'), 'command_outbox', ['command_id'], unique=False)
    op.create_index(op.f('ix_command_outbox_published_at'), 'command_outbox', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_outbox_published_at'), table_name='command_outbox')
    op.drop_index(op.f('ix_command_outbox_command_id'), table_name='command_outbox')
    op.drop_index(op.f('ix_command_outbox_available_at'), table_name='command_outbox')
    op.drop_table('command_outbox')
    op.drop_index(op.f('ix_command_inbox_received_at'), table_name='command_inbox')
    op.drop_index(op.f('ix_command_inbox_outbox_id'), table_name='command_inbox')
    op.drop_index(op.f('ix_command_inbox_command_id'), table_name='command_inbox')
    op.drop_table('command_inbox')
    op.drop_index(op.f('ix_command_events_event_type'), table_name='command_events')
    op.drop_index(op.f('ix_command_events_created_at'), table_name='command_events')
    op.drop_index(op.f('ix_command_events_command_id'), table_name='command_events')
    op.drop_table('command_events')
    op.drop_index(op.f('ix_command_attempts_command_id'), table_name='command_attempts')
    op.drop_table('command_attempts')
    op.drop_index(op.f('ix_command_approvals_operator'), table_name='command_approvals')
    op.drop_index(op.f('ix_command_approvals_command_id'), table_name='command_approvals')
    op.drop_table('command_approvals')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_triage_templates_key'), table_name='triage_templates')
    op.drop_table('triage_templates')
    op.drop_index(op.f('ix_triage_rules_priority'), table_name='triage_rules')
    op.drop_table('triage_rules')
    op.drop_index(op.f('ix_triage_audit_log_task_id'), table_name='triage_audit_log')
    op.drop_index(op.f('ix_triage_audit_log_operator_id'), table_name='triage_audit_log')
    op.drop_index(op.f('ix_triage_audit_log_created_at'), table_name='triage_audit_log')
    op.drop_table('triage_audit_log')
    op.execute("DROP INDEX IF EXISTS idx_task_kb_hnsw")
    op.drop_index(op.f('ix_task_knowledge_base_task_id'), table_name='task_knowledge_base')
    op.drop_index(op.f('ix_task_knowledge_base_quality_score'), table_name='task_knowledge_base')
    op.drop_table('task_knowledge_base')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_security_audit_log_outcome'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_event_type'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_created_at'), table_name='security_audit_log')
    op.drop_table('security_audit_log')
    op.drop_index(op.f('ix_rule_audit_log_entity_type'), table_name='rule_audit_log')
    op.drop_index(op.f('ix_rule_audit_log_entity_id'), table_name='rule_audit_log')
    op.drop_index(op.f('ix_rule_audit_log_created_at'), table_name='rule_audit_log')
    op.drop_index(op.f('ix_rule_audit_log_changed_by'), table_name='rule_audit_log')
    op.drop_table('rule_audit_log')
    op.drop_index(op.f('ix_job_log_task_id'), table_name='job_log')
    op.drop_index(op.f('ix_job_log_status'), table_name='job_log')
    op.drop_index(op.f('ix_job_log_source'), table_name='job_log')
    op.drop_index(op.f('ix_job_log_initiator'), table_name='job_log')
    op.drop_index(op.f('ix_job_log_idempotency_key'), table_name='job_log')
    op.drop_index(op.f('ix_job_log_created_at'), table_name='job_log')
    op.drop_index(op.f('ix_job_log_command_type'), table_name='job_log')
    op.drop_table('job_log')
    op.drop_index(op.f('ix_desktop_launch_log_token_hash'), table_name='desktop_launch_log')
    op.drop_index(op.f('ix_desktop_launch_log_task_id'), table_name='desktop_launch_log')
    op.drop_index(op.f('ix_desktop_launch_log_status'), table_name='desktop_launch_log')
    op.drop_index(op.f('ix_desktop_launch_log_initiator'), table_name='desktop_launch_log')
    op.drop_index(op.f('ix_desktop_launch_log_host'), table_name='desktop_launch_log')
    op.drop_index(op.f('ix_desktop_launch_log_expires_at'), table_name='desktop_launch_log')
    op.drop_index(op.f('ix_desktop_launch_log_created_at'), table_name='desktop_launch_log')
    op.drop_table('desktop_launch_log')
    op.drop_index(op.f('ix_commands_task_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_status'), table_name='commands')
    op.drop_index(op.f('ix_commands_source'), table_name='commands')
    op.drop_index(op.f('ix_commands_initiator'), table_name='commands')
    op.drop_index(op.f('ix_commands_idempotency_key'), table_name='commands')
    op.drop_index(op.f('ix_commands_executor'), table_name='commands')
    op.drop_index(op.f('ix_commands_created_at'), table_name='commands')
    op.drop_index(op.f('ix_commands_action'), table_name='commands')
    op.drop_table('commands')
    op.drop_table('action_policies')
    # ### end Alembic commands ###
