"""Strict domain contracts shared by decisioning and execution services."""

from shared.domain.models import (
    ActionProposed,
    ClarificationRequired,
    CreateUserParameters,
    DecisionOutcome,
    DecisionOutcomeAdapter,
    Evidence,
    ExtractedPersonCandidate,
    ExtractedTicketFacts,
    ManualReviewRequired,
    NoMatch,
    PersonCandidate,
    ResolutionProposed,
    TicketFacts,
    ValidPerson,
    ValidationError,
)
from shared.domain.person import normalize_person_name, validate_person_candidate
from shared.domain.scenario import (
    CandidateOutcome,
    DecisionGates,
    DecisionEnvelope,
    DecisionResponse,
    ExecutionPlan,
    FactBag,
    FactObservation,
    FactRequirement,
    FactSensitivity,
    FactSource,
    FactState,
    PlanStep,
    RejectedCandidate,
    ResolvedFact,
    ScenarioDefinition,
    ScenarioMatch,
    SynthesisProposal,
)

__all__ = [
    "ActionProposed",
    "ClarificationRequired",
    "CreateUserParameters",
    "DecisionOutcome",
    "DecisionOutcomeAdapter",
    "Evidence",
    "ExtractedPersonCandidate",
    "ExtractedTicketFacts",
    "ManualReviewRequired",
    "NoMatch",
    "PersonCandidate",
    "ResolutionProposed",
    "TicketFacts",
    "ValidPerson",
    "ValidationError",
    "CandidateOutcome",
    "DecisionGates",
    "DecisionEnvelope",
    "DecisionResponse",
    "ExecutionPlan",
    "FactBag",
    "FactObservation",
    "FactRequirement",
    "FactSensitivity",
    "FactSource",
    "FactState",
    "PlanStep",
    "RejectedCandidate",
    "ResolvedFact",
    "ScenarioDefinition",
    "ScenarioMatch",
    "SynthesisProposal",
    "normalize_person_name",
    "validate_person_candidate",
]
